### ISSUE TITLE
Feature suggestion - search/filter

### ISSUE THREAD

**Issue by jakewarren** [zianwar/gitmarks#1]
It would be awesome to have a search or filter capability to be able to search within the repo name and descriptions.

**Comment by zianwar** [comment]
Hey @jakewarren, 

Thanks for the suggestion!

Since I'm rendering all the repositories in a single page, you can just use the browser search (cmd/ctrl + F), it's reliable and just works across all fields (repo name, descriptions...).

Let me know if there's an issue with that!

**Comment by jakewarren** [comment]
@zianwar thanks, I didn't word it very well but I meant being able to apply your search specifically to either repo names only or descriptions only. 

I have no idea how hard that would be or if other users would even find it useful, just an idea. :)
